# 开发环境
server:
  port: 8081
# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://47.120.67.11:23306/spring-security?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=false&characterEncoding=UTF-8
        username: root
        password: A1helloworld.
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT version()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: false
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: b612
        login-password: 123456
      filter:
        stat:
          enabled: false
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  # redis 配置
  redis:
    # 地址
    host: 47.120.67.11
    # 端口，默认为6379
    port: 26379
    # 数据库索引
    database: 3
    # 密码
    password: A1helloworld.
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cps.material.model  #所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #指定 MyBatis 所用日志的具体实现，未指定时将自动查找
    map-underscore-to-camel-case: true #开启自动驼峰命名规则（camel case）映射
    # lazy-loading-enabled: true #开启延时加载开关
    # aggressive-lazy-loading: false #将积极加载改为消极加载（即按需加载）,默认值就是false
    # lazy-load-trigger-methods: "" #阻挡不相干的操作触发，实现懒加载
    # cache-enabled: true #打开全局缓存开关（二级环境），默认值就是true

# 配置spring-security
jwt:
  secret: b612-very-secure-and-long-secret-key-here-32-bytes-min-1234567890
